### ISSUE TITLE
Not longer compatible with numpy 2.0

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [scikit-hep/ragged#56]
So far, I've hit the fact that `np.array_api` no longer exists:

"""
NumPy 1.22.0 was the first version to include support for the array API standard, via a separate numpy.array_api submodule. This module was marked as experimental (it emitted a warning on import) and removed in NumPy 2.0 because full support was included in the main namespace.
"""

So I put in this stanza in the tests:

```
if np.__version__ < '2.0.0':  # not a robust way to check version!
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        import numpy.array_api as xp
else:
    xp = np
```
but hit some other snags:

```
E   AttributeError: module 'numpy' has no attribute '_dtypes'. Did you mean: 'dtypes'?
```

For now, I'm going to go back to <2.0 -- but hopefully I'll be able to clean this up later, if someone doesn't beat me to it.

(maybe numpy should be pinned to <2 for now?)

**Comment by ianna** [comment]
fixed in https://github.com/scikit-hep/ragged/pull/60
